Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2019-11, with the labels that each got.

#9 Update travis api key
  .travis.yml
Labels: dco-signoff: yes

#10 Update travis token.
  .travis.yml
Labels: dco-signoff: yes

#11 Publish proper tag to quay.
  .travis.yml
Labels: dco-signoff: yes, size/XS

#12 Still fighting travis env variables.
  .travis.yml
Labels: dco-signoff: yes, size/XS

#13 Merge pull request #12 from awels/travis3
  .travis.yml
Labels: dco-signoff: no

#15 Remove golang 1.13 specific optional compiler flag
  Makefile
Labels: dco-signoff: yes, size/XS

#14 Update selinux command to modern version.
  README.md
Labels: dco-signoff: yes, size/XS

#18 README improvements
  README.md
Labels: dco-signoff: yes, size/S

#19 Update travis push to properly push container
  .travis.yml
Labels: dco-signoff: yes, size/XS

#20 Don't manage storage class with operator.
  README.md
  deploy/operator.yaml
  deploy/storageclass-immediate.yaml
  deploy/storageclass-wffc.yaml
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/controller.go
Labels: dco-signoff: yes, size/L

#22 Don't concat the image name, just take as is.
  deploy/operator.yaml
  pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  tools/csv-generator.go
Labels: dco-signoff: yes, size/M

#24 Fix container image to be full image.
  deploy/operator.yaml
Labels: dco-signoff: yes, size/XS

#26 Fix csv generator to take operator image string.
  tools/csv-generator.go
  tools/helper/helper.go
Labels: dco-signoff: yes, size/XS

#29 Add csv-generator to release container
  Dockerfile
Labels: dco-signoff: yes, size/XS

#31 make image wasn't building csv-generator
  Makefile
Labels: dco-signoff: yes, size/XS

#33 Fix: Can't find executable in image
  Dockerfile
Labels: dco-signoff: yes, size/XS
