Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2019-10, with the labels that each got.

#3 Update travis to release on version tags.
  .travis.yml
Labels: dco-signoff: yes, size/M

#4 Fix operator yaml to pull right image.
  deploy/operator.yaml
Labels: dco-signoff: yes

#5 Support WaitForFirstConsumer
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/rbac.go
Labels: dco-signoff: yes, size/S

#6 Update the documentation to properly install in the hostpath provisioner namespace
  README.md
  deploy/cluster_role.yaml
  deploy/cluster_role_binding.yaml
  deploy/crds/hostpathprovisioner.kubevirt.io_hostpathprovisioners_crd.yaml
  deploy/hostpathprovisioner_cr.yaml
  deploy/namespace.yaml
  deploy/operator.yaml
  deploy/service_account.yaml
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/rbac.go
Labels: dco-signoff: yes, size/XL

#7 Remove -trimpath which is only available in golang-1.13
  Makefile
Labels: dco-signoff: yes, size/XS

#8 Fixed up rbac some more to work with OKD/OS/K8s
  README.md
  deploy/operator.yaml
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/rbac.go
Labels: dco-signoff: yes, size/M
