Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2020-07, with the labels that each got.

#73 Add a MachineConfig file for SELinux-specific configuration
  README.md
  contrib/machineconfig-selinux-hpp.yaml
Labels: dco-signoff: yes, size/M

#75 Missed a few spots where naming prefix was still string.
  deploy/operator.yaml
  tools/csv-generator.go
  tools/helper/helper.go
Labels: dco-signoff: yes, size/XS

#76 Switch to using apiextensions v1 instead of v1beta
  deploy/operator.yaml
  tools/helper/helper.go
Labels: dco-signoff: yes, size/L

#78 Add node upgrade scripts to contrib
  contrib/README.md
  contrib/export.sh
  contrib/export_pv.py
  contrib/import.sh
  contrib/import_pv.py
Labels: dco-signoff: yes, size/L

#77 Generate events on operator actions. The following actions generate
  pkg/controller/hostpathprovisioner/common.go
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/cr.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/scc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1/zz_generated.defaults.go
  vendor/k8s.io/apimachinery/pkg/api/equality/semantic.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL

#79 Fixed CRD definition in helper, so csv-generator has proper CRD
  tools/helper/helper.go
  tools/yaml-dumper/yaml-dumper.go
Labels: dco-signoff: yes, size/L

#81 Fix comment to say HPP instead of CDI
  tools/yaml-dumper/yaml-dumper.go
Labels: dco-signoff: yes, size/XS
