Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2021-01, with the labels that each got.

#96 Add missing description for ImagePullPolicy
  pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
Labels: dco-signoff: yes, size/S

#95 Fix reconcile to properly fix changes and respond to changes in the CR
  deploy/operator.yaml
  pkg/controller/hostpathprovisioner/contoller_test.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/scc.go
  pkg/controller/hostpathprovisioner/util.go
Labels: dco-signoff: yes, size/XL

#101 Fix README deploy link
  README.md
Labels: dco-signoff: yes, size/XS
