Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2021-08, with the labels that each got.

#114 Add relationship labels
  pkg/controller/hostpathprovisioner/common.go
  pkg/controller/hostpathprovisioner/controller_suite_test.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/scc.go
  pkg/controller/hostpathprovisioner/serviceaccount.go
  pkg/controller/hostpathprovisioner/util.go
  tools/helper/helper.go
Labels: dco-signoff: yes, size/L

#115 Don't reconcile over spec.selector changes
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/XS

#116 Change MaxUnavailable amount of replicas during update from 1->10%
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/S

#119 Update CRD to include disableCSI for hpp CR
  deploy/operator.yaml
  pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  vendor/github.com/onsi/ginkgo/extensions/table/table.go
  vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go
Labels: dco-signoff: yes, size/XXL

#120 Update CRD to be v1
  Makefile
  deploy/operator.yaml
  go.mod
  go.sum
Labels: dco-signoff: yes, size/L

#121 Fixed disableCsi not working properly.
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/csidriver.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/serviceaccount.go
Labels: dco-signoff: yes, size/L

#122 Allow delete of csi driver
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/csidriver.go
Labels: dco-signoff: yes, size/S

#123 Update generated SCC to use with CSI.
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/scc.go
Labels: dco-signoff: yes, size/M

#124 Enabled csi storage capacity configuration.
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/S

#126 Report capacity for immediate binding sc.
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/XS

#127 Modify the daemonset parameters to work with topology
  go.mod
  go.sum
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/scc.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/S
