Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2021-11, with the labels that each got.

#152 Add snapshot featuregate support
  go.mod
  go.sum
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  tools/helper/crd_generated.go
  vendor/k8s.io/client-go/discovery/fake/discovery.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/L, approved, lgtm

#153 Switch listType to atomic
  deploy/operator.yaml
  pkg/apis/hostpathprovisioner/v1alpha1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1alpha1/zz_generated.openapi.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#155 Generate operator deployment in csv-generator
  deploy/operator.yaml
  tools/crd-generator/crd-generator.go
  tools/csv-generator.go
  tools/helper/crd_generated.go
  tools/helper/helper.go
  tools/helper/operator_deployment_generated.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm

#154 Add alerts infra & simple alert
  cmd/manager/main.go
  deploy/operator.yaml
  go.mod
  go.sum
  pkg/controller/hostpathprovisioner/common.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
  pkg/controller/hostpathprovisioner/scc.go
  tools/helper/helper.go
  tools/helper/operator_deployment_generated.go
  tools/helper/role_generated.go
  vendor/github.com/coreos/prometheus-operator/LICENSE
  vendor/github.com/coreos/prometheus-operator/NOTICE
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/doc.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/register.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/thanos_types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/types.go
  vendor/github.com/coreos/prometheus-operator/pkg/apis/monitoring/v1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, approved, lgtm

#159 Replace the priorityClass to kubevirt-cluster-critical
  tools/helper/helper.go
Labels: dco-signoff: yes, size/XS, release-note, approved, lgtm

#157 Drop crd-generator from csv-generator target
  Makefile
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#160 Fix SCC creation/deletion for CSI driver.
  deploy/operator.yaml
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/scc.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#164 Update fedora version to 34
  Dockerfile
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#163 Reconcile role and role binding created by operator
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/rbac.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#165 Add degraded alert
  go.mod
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/cr.go
  pkg/controller/hostpathprovisioner/prometheus.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#161 Ensure the daemonset pods all have cpu/mem request set.
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#166 Fix how we reconcile the prometheus resources to avoid spam
  pkg/controller/hostpathprovisioner/prometheus.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#168 Added proper resource on webhook definition
  tools/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#169 Sync generated resources
  tools/helper/cluster_role_generated.go
  tools/helper/crd_generated.go
  tools/helper/operator_deployment_generated.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm

#170 Don't put unnecessary labels in .spec.selector
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#172 [release-v0.10] Manual cherrypick of #170
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#171 Change how leader election works in combination with ready probe
  cmd/manager/main.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#174 Fix permissions after updating leader election mechanism.
  deploy/operator.yaml
  tools/helper/role_generated.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm
