Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2021-12, with the labels that each got.

#175 Allow usage of PVCTemplate as storage pool source.
  Dockerfile
  Makefile
  cmd/mounter/chroot.go
  cmd/mounter/main.go
  deploy/hostpathprovisioner_cr.yaml
  deploy/operator.yaml
  go.mod
  hack/build-mounter.sh
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_types.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.deepcopy.go
  pkg/apis/hostpathprovisioner/v1beta1/zz_generated.openapi.go
  pkg/controller/hostpathprovisioner/common.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/csidriver.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
  pkg/controller/hostpathprovisioner/rbac_test.go
  pkg/controller/hostpathprovisioner/scc_test.go
  pkg/controller/hostpathprovisioner/serviceaccount.go
  pkg/controller/hostpathprovisioner/serviceaccount_test.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
  tools/helper/crd_generated.go
  tools/helper/operator_deployment_generated.go
  tools/helper/role_generated.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/doc.go
  vendor/github.com/operator-framework/operator-sdk/pkg/leader/leader.go
  vendor/modules.txt
Labels: dco-signoff: yes, size/XXL, release-note, approved, lgtm

#179 Only start legacy provisioner on legacy CR
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/csidriver.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/scc.go
  pkg/controller/hostpathprovisioner/scc_test.go
  pkg/controller/hostpathprovisioner/serviceaccount.go
  pkg/controller/hostpathprovisioner/serviceaccount_test.go
Labels: dco-signoff: yes, release-note, size/XL, approved, lgtm

#180 Fix bug where the legacy storage pool kept being added to the status.
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#181 Fix bug where path was not being created if it didn't exist on the host already.
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#182 Stop deploy the csi external health monitor
  deploy/operator.yaml
  pkg/controller/hostpathprovisioner/common.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/rbac.go
  pkg/controller/hostpathprovisioner/serviceaccount.go
  tools/csv-generator.go
  tools/helper/cluster_role_generated.go
  tools/helper/helper.go
  tools/helper/operator_deployment_generated.go
  tools/helper/role_generated.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm

#176 Add common labels into alert definitions
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
Labels: dco-signoff: yes, size/S, release-note, needs-ok-to-test, approved, lgtm

#183 Remove 1 storage pool limit
  README.md
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
Labels: dco-signoff: yes, release-note, size/L, approved, lgtm

#185 Hash names if length over label or volume name max
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
  pkg/controller/hostpathprovisioner/util.go
Labels: dco-signoff: yes, release-note, size/L, approved, lgtm

#173 [release-v0.9] Manual cherrypick of #170
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#188 Mention minimum k8s version
  README.md
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#189 Update CSI driver to allow for fsGroup policy.
  pkg/controller/hostpathprovisioner/csidriver.go
  pkg/controller/hostpathprovisioner/daemonset.go
Labels: dco-signoff: yes, size/XS, release-note, approved, lgtm

#187 Don't delete/update over immutable CSIDriver fields
  pkg/controller/hostpathprovisioner/csidriver.go
  pkg/controller/hostpathprovisioner/csidriver_test.go
  pkg/controller/hostpathprovisioner/rbac_test.go
  pkg/controller/hostpathprovisioner/scc_test.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm

#191 Rename legacy storage class example
  deploy/storageclass-wffc-legacy.yaml
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#190 Enable ephemeral volumes in CSIDriver object
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/csidriver.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#192 Fix CSV generator to update operator deployment environment variables
  tools/helper/helper.go
Labels: dco-signoff: yes, size/XS, release-note, approved, lgtm

#177 Add tool to generate metrics documentation
  Makefile
  docs/metrics.md
  pkg/controller/hostpathprovisioner/metrics.go
  pkg/controller/hostpathprovisioner/prometheus.go
  tools/metricsdocs/fakeCollector.go
  tools/metricsdocs/metricsdocs.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm
