Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2021-09, with the labels that each got.

#131 Set requests on operator deployment
  deploy/operator.yaml
  tools/helper/helper.go
Labels: dco-signoff: yes, size/S

#133 Avoid references to master branch - renamed to main
  README.md
  tools/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#134 Add a script to check for new additions of non-inclusive language
  Makefile
  hack/language.sh
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm
