Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2022-01, with the labels that each got.

#194 Ensure storage pool deployment sets service account
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#195 Remove annotations from prometheus recording rules
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#199 Update approach to fetch metrics
  pkg/controller/hostpathprovisioner/metrics.go
  pkg/controller/hostpathprovisioner/prometheus.go
  tools/metricsdocs/fakeCollector.go
  tools/metricsdocs/metricsdocs.go
Labels: dco-signoff: yes, release-note-none, size/L, approved, lgtm

#201 Update ALM example to show new format.
  tools/csv-generator.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#202 Fix MarkFailed not being updated in CR properly
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#209 Fix the JSON format of the CSV's `alm-examples` field
  tools/csv-generator.go
Labels: dco-signoff: yes, size/S, release-note, approved, lgtm

#211 Fix issue with basic and pvcTemplate causing npe when removing hpp cr
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#207 Make DaemonSet metrics scrapable
  pkg/controller/hostpathprovisioner/daemonset.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#213 Stop endless reconcile
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/storagepool.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#216 Replace operator image environment variable during csv generation.
  tools/helper/helper.go
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm
