Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2023-08, with the labels that each got.

#345 Change `kubevirt_hpp_operator_up_total` name
  docs/metrics.md
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
  tools/prom-metrics-collector/metrics_collector.go
Labels: dco-signoff: yes, size/S, release-note, approved, lgtm

#348 Correct typo in csv generator build command
  hack/build-csv-generator.sh
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#353 Fix linter errors
  cmd/mounter/mounter_suite_test.go
  cmd/mounter/mounter_test.go
  pkg/apis/hostpathprovisioner/v1beta1/api_suite_test.go
  pkg/apis/hostpathprovisioner/v1beta1/hostpathprovisioner_webhook_test.go
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/controller/hostpathprovisioner/controller_suite_test.go
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/cryptopolicy_test.go
  pkg/controller/hostpathprovisioner/csidriver_test.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
  pkg/controller/hostpathprovisioner/rbac_test.go
  pkg/controller/hostpathprovisioner/scc_test.go
  pkg/controller/hostpathprovisioner/serviceaccount_test.go
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
  version/version.go
  version/version_suite_test.go
  version/version_test.go
Labels: dco-signoff: yes, release-note-none, size/M, approved, lgtm

#357 Update HPP CR conditions correctly when degraded
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/controller_test.go
Labels: dco-signoff: yes, size/S, release-note, approved, lgtm

#356 [release-v0.16] Change `kubevirt_hpp_operator_up_total` name
  docs/metrics.md
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/prometheus.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#358 bump k8s.io/client-go dep for discovery client fixes
  deploy/operator.yaml
  go.mod
  go.sum
  tools/helper/crd_generated.go
  vendor/github.com/google/uuid/hash.go
  vendor/github.com/google/uuid/null.go
  vendor/github.com/google/uuid/sql.go
  vendor/github.com/google/uuid/uuid.go
  vendor/github.com/google/uuid/version4.go
  vendor/k8s.io/api/batch/v1/generated.proto
  vendor/k8s.io/api/batch/v1/types.go
  vendor/k8s.io/api/batch/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/core/v1/generated.proto
  vendor/k8s.io/api/core/v1/types.go
  vendor/k8s.io/api/core/v1/types_swagger_doc_generated.go
  vendor/k8s.io/api/resource/v1alpha1/generated.proto
  vendor/k8s.io/api/resource/v1alpha1/types.go
  vendor/k8s.io/apimachinery/pkg/runtime/converter.go
  vendor/k8s.io/client-go/applyconfigurations/internal/internal.go
  vendor/k8s.io/client-go/discovery/aggregated_discovery.go
  vendor/k8s.io/client-go/discovery/discovery_client.go
  vendor/k8s.io/client-go/openapi/client.go
  vendor/k8s.io/client-go/openapi/groupversion.go
  vendor/k8s.io/client-go/tools/cache/controller.go
  vendor/k8s.io/client-go/tools/cache/delta_fifo.go
  vendor/k8s.io/client-go/tools/cache/shared_informer.go
  vendor/k8s.io/client-go/transport/cache.go
  vendor/k8s.io/client-go/util/cert/cert.go
  vendor/modules.txt
Labels: dco-signoff: yes, release-note, size/XL, approved, lgtm

#364 Add relationship labels to pods created by storage pool
  pkg/controller/hostpathprovisioner/storagepool.go
  pkg/controller/hostpathprovisioner/storagepool_test.go
Labels: dco-signoff: yes, size/S, release-note, approved, lgtm
