Repository kubevirt/hostpath-provisioner-operator, pull requests merged in 2024-02, with the labels that each got.

#431 Fix linter complaining about unused variables
  pkg/controller/hostpathprovisioner/controller.go
  pkg/controller/hostpathprovisioner/daemonset_test.go
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#428 Audit RBAC, ensure no global (*) permissions
  deploy/operator.yaml
  pkg/controller/hostpathprovisioner/controller_test.go
  pkg/controller/hostpathprovisioner/rbac.go
  tools/helper/cluster_role_generated.go
  tools/helper/role_generated.go
Labels: dco-signoff: yes, size/M, release-note, approved, lgtm

#432 Restore permissions to lease in the deployment namespace so the operator can give them to the csi-provisioner
  deploy/operator.yaml
Labels: dco-signoff: yes, release-note-none, size/XS, approved, lgtm

#433 Use golang available in builder container instead of trying to set it manually.
  Dockerfile
  Makefile
  hack/build-crd-generator.sh
  hack/build-csv-generator.sh
  hack/build-mounter.sh
  hack/build-operator.sh
  hack/common.sh
  hack/run-unit-tests.sh
Labels: dco-signoff: yes, release-note-none, size/S, approved, lgtm

#439 Revert to using controller-runtime registry for metrics
  pkg/monitoring/metrics/metrics.go
Labels: dco-signoff: yes, size/XS, release-note, approved, lgtm
